{"metadata":{"symbolKind":"module","role":"collection","roleHeading":"Framework","modules":[{"name":"FeltEmbeddedCare"}],"externalID":"FeltEmbeddedCare","title":"FeltEmbeddedCare"},"topicSections":[{"anchor":"Articles","generated":true,"title":"Articles","identifiers":["doc:\/\/clinic.felt.EmbeddedCare\/documentation\/FeltEmbeddedCare\/Documentation"]},{"title":"Classes","generated":true,"identifiers":["doc:\/\/clinic.felt.EmbeddedCare\/documentation\/FeltEmbeddedCare\/ComponentView","doc:\/\/clinic.felt.EmbeddedCare\/documentation\/FeltEmbeddedCare\/EmbeddedCare","doc:\/\/clinic.felt.EmbeddedCare\/documentation\/FeltEmbeddedCare\/FullScreenViewController"],"anchor":"Classes"},{"generated":true,"identifiers":["doc:\/\/clinic.felt.EmbeddedCare\/documentation\/FeltEmbeddedCare\/Account","doc:\/\/clinic.felt.EmbeddedCare\/documentation\/FeltEmbeddedCare\/Component","doc:\/\/clinic.felt.EmbeddedCare\/documentation\/FeltEmbeddedCare\/FullScreenExperience","doc:\/\/clinic.felt.EmbeddedCare\/documentation\/FeltEmbeddedCare\/FullScreenView","doc:\/\/clinic.felt.EmbeddedCare\/documentation\/FeltEmbeddedCare\/Patient"],"anchor":"Structures","title":"Structures"},{"title":"Enumerations","identifiers":["doc:\/\/clinic.felt.EmbeddedCare\/documentation\/FeltEmbeddedCare\/ComponentExperience","doc:\/\/clinic.felt.EmbeddedCare\/documentation\/FeltEmbeddedCare\/FeatureGate"],"anchor":"Enumerations","generated":true}],"variants":[{"paths":["\/documentation\/feltembeddedcare"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/feltembeddedcare"]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/clinic.felt.EmbeddedCare\/documentation\/FeltEmbeddedCare"},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"hierarchy":{"paths":[[]]},"references":{"doc://clinic.felt.EmbeddedCare/documentation/FeltEmbeddedCare":{"url":"\/documentation\/feltembeddedcare","kind":"symbol","type":"topic","abstract":[],"title":"FeltEmbeddedCare","role":"collection","identifier":"doc:\/\/clinic.felt.EmbeddedCare\/documentation\/FeltEmbeddedCare"},"doc://clinic.felt.EmbeddedCare/documentation/FeltEmbeddedCare/FullScreenExperience":{"role":"symbol","identifier":"doc:\/\/clinic.felt.EmbeddedCare\/documentation\/FeltEmbeddedCare\/FullScreenExperience","url":"\/documentation\/feltembeddedcare\/fullscreenexperience","abstract":[{"text":"An experience that is meant to take over your app’s UI","type":"text"}],"navigatorTitle":[{"text":"FullScreenExperience","kind":"identifier"}],"type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"FullScreenExperience","kind":"identifier"}],"title":"FullScreenExperience","kind":"symbol"},"doc://clinic.felt.EmbeddedCare/documentation/FeltEmbeddedCare/Documentation":{"type":"topic","kind":"article","role":"article","abstract":[{"type":"text","text":"Felt offers a seamless telehealth experience inside health apps. Our platform handles the full user lifecycle, including onboarding, payments, and doctor visits, ensuring a cohesive healthcare experience."}],"title":"Felt Embedded Care iOS SDK","identifier":"doc:\/\/clinic.felt.EmbeddedCare\/documentation\/FeltEmbeddedCare\/Documentation","url":"\/documentation\/feltembeddedcare\/documentation"},"doc://clinic.felt.EmbeddedCare/documentation/FeltEmbeddedCare/FeatureGate":{"navigatorTitle":[{"kind":"identifier","text":"FeatureGate"}],"url":"\/documentation\/feltembeddedcare\/featuregate","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FeatureGate"}],"title":"FeatureGate","type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/clinic.felt.EmbeddedCare\/documentation\/FeltEmbeddedCare\/FeatureGate","abstract":[{"text":"An enumeration of known features that can be checked for the current account","type":"text"}]},"doc://clinic.felt.EmbeddedCare/documentation/FeltEmbeddedCare/FullScreenViewController":{"type":"topic","abstract":[{"type":"text","text":"A "},{"type":"codeVoice","code":"UIViewController"},{"type":"text","text":" used to integrate Felt’s embedded care content."},{"text":" ","type":"text"},{"type":"text","text":"The view controller is meant to be presented modally or in a way that takes up the majority of your app’s UI,"},{"text":" ","type":"text"},{"type":"text","text":"such as a tab in a tab bar."}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"FullScreenViewController","kind":"identifier"}],"identifier":"doc:\/\/clinic.felt.EmbeddedCare\/documentation\/FeltEmbeddedCare\/FullScreenViewController","navigatorTitle":[{"kind":"identifier","text":"FullScreenViewController"}],"url":"\/documentation\/feltembeddedcare\/fullscreenviewcontroller","title":"FullScreenViewController","kind":"symbol"},"doc://clinic.felt.EmbeddedCare/documentation/FeltEmbeddedCare/EmbeddedCare":{"role":"symbol","url":"\/documentation\/feltembeddedcare\/embeddedcare","abstract":[{"text":"The primary interaction point with Felt’s embedded care features","type":"text"}],"type":"topic","identifier":"doc:\/\/clinic.felt.EmbeddedCare\/documentation\/FeltEmbeddedCare\/EmbeddedCare","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"EmbeddedCare","kind":"identifier"}],"kind":"symbol","title":"EmbeddedCare","navigatorTitle":[{"text":"EmbeddedCare","kind":"identifier"}]},"doc://clinic.felt.EmbeddedCare/documentation/FeltEmbeddedCare/ComponentExperience":{"identifier":"doc:\/\/clinic.felt.EmbeddedCare\/documentation\/FeltEmbeddedCare\/ComponentExperience","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ComponentExperience"}],"navigatorTitle":[{"text":"ComponentExperience","kind":"identifier"}],"role":"symbol","type":"topic","url":"\/documentation\/feltembeddedcare\/componentexperience","title":"ComponentExperience","abstract":[{"text":"An experience associated with a component view that is displayed alongside","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"your app’s native content"}]},"doc://clinic.felt.EmbeddedCare/documentation/FeltEmbeddedCare/Patient":{"type":"topic","identifier":"doc:\/\/clinic.felt.EmbeddedCare\/documentation\/FeltEmbeddedCare\/Patient","kind":"symbol","role":"symbol","title":"Patient","url":"\/documentation\/feltembeddedcare\/patient","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"Patient","kind":"identifier"}],"navigatorTitle":[{"text":"Patient","kind":"identifier"}],"abstract":[{"text":"Represents information about a patient on an account","type":"text"}]},"doc://clinic.felt.EmbeddedCare/documentation/FeltEmbeddedCare/Account":{"title":"Account","identifier":"doc:\/\/clinic.felt.EmbeddedCare\/documentation\/FeltEmbeddedCare\/Account","url":"\/documentation\/feltembeddedcare\/account","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Account","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"Account"}],"kind":"symbol","abstract":[{"type":"text","text":"Represents information about the currently logged in user account"}],"role":"symbol","type":"topic"},"doc://clinic.felt.EmbeddedCare/documentation/FeltEmbeddedCare/FullScreenView":{"kind":"symbol","abstract":[{"text":"A ","type":"text"},{"code":"SwiftUI","type":"codeVoice"},{"type":"text","text":" "},{"code":"View","type":"codeVoice"},{"type":"text","text":" used to integrate Felt’s embedded care content."},{"type":"text","text":" "},{"text":"The view is meant to be presented modally or in a way that takes up the majority of your app’s UI,","type":"text"},{"type":"text","text":" "},{"type":"text","text":"such as a tab in a tab bar."}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"FullScreenView","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/clinic.felt.EmbeddedCare\/documentation\/FeltEmbeddedCare\/FullScreenView","navigatorTitle":[{"text":"FullScreenView","kind":"identifier"}],"title":"FullScreenView","url":"\/documentation\/feltembeddedcare\/fullscreenview","type":"topic"},"doc://clinic.felt.EmbeddedCare/documentation/FeltEmbeddedCare/ComponentView":{"abstract":[{"text":"A ","type":"text"},{"code":"UIView","type":"codeVoice"},{"text":" used to integrate Felt’s embedded care content alongside your app’s native ","type":"text"},{"type":"codeVoice","code":"UIKit"},{"type":"text","text":" content."}],"identifier":"doc:\/\/clinic.felt.EmbeddedCare\/documentation\/FeltEmbeddedCare\/ComponentView","url":"\/documentation\/feltembeddedcare\/componentview","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ComponentView","kind":"identifier"}],"title":"ComponentView","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ComponentView"}],"type":"topic"},"doc://clinic.felt.EmbeddedCare/documentation/FeltEmbeddedCare/Component":{"abstract":[{"text":"A ","type":"text"},{"type":"codeVoice","code":"View"},{"text":" used to integrate Felt’s embedded care content alongside your app’s native ","type":"text"},{"type":"codeVoice","code":"SwiftUI"},{"text":" content","type":"text"}],"role":"symbol","url":"\/documentation\/feltembeddedcare\/component","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Component"}],"title":"Component","identifier":"doc:\/\/clinic.felt.EmbeddedCare\/documentation\/FeltEmbeddedCare\/Component","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"Component","kind":"identifier"}],"type":"topic"},"doc://clinic.felt.EmbeddedCare/documentation/FeltEmbeddedCare/FeltEmbeddedCareVersionNumber":{"title":"FeltEmbeddedCareVersionNumber","kind":"symbol","type":"topic","identifier":"doc:\/\/clinic.felt.EmbeddedCare\/documentation\/FeltEmbeddedCare\/FeltEmbeddedCareVersionNumber","url":"\/documentation\/feltembeddedcare\/feltembeddedcareversionnumber","role":"symbol","fragments":[{"text":"FeltEmbeddedCareVersionNumber","kind":"identifier"}],"abstract":[{"type":"text","text":"Project version number for FeltEmbeddedCare."}]},"doc://clinic.felt.EmbeddedCare/documentation/FeltEmbeddedCare/FeltEmbeddedCareVersionString":{"abstract":[{"type":"text","text":"Project version string for FeltEmbeddedCare."}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/clinic.felt.EmbeddedCare\/documentation\/FeltEmbeddedCare\/FeltEmbeddedCareVersionString","fragments":[{"text":"FeltEmbeddedCareVersionString","kind":"identifier"}],"url":"\/documentation\/feltembeddedcare\/feltembeddedcareversionstring","type":"topic","title":"FeltEmbeddedCareVersionString"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/topicSections","op":"replace","value":[{"title":"Articles","generated":true,"identifiers":["doc:\/\/clinic.felt.EmbeddedCare\/documentation\/FeltEmbeddedCare\/Documentation"],"anchor":"Articles"},{"anchor":"Variables","generated":true,"identifiers":["doc:\/\/clinic.felt.EmbeddedCare\/documentation\/FeltEmbeddedCare\/FeltEmbeddedCareVersionNumber","doc:\/\/clinic.felt.EmbeddedCare\/documentation\/FeltEmbeddedCare\/FeltEmbeddedCareVersionString"],"title":"Variables"}]},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"}]}]}